apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-typescript-debug-example
spec:
  selector:
    matchLabels:
      app: node-typescript-debug-example
  replicas: 1
  template:
    metadata:
      labels:
        app: node-typescript-debug-example
    spec:
      containers:
        - name: node-typescript-debug-example
          image: node-typescript-debug-example:v1
          imagePullPolicy: Never
          command: ['node dist/index.js']
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - mountPath: /app/dist
          #     name: app-mount
          livenessProbe:
            httpGet:
              path: /
              port: 80
          env:
            - name: PORT
              value: '80'
      # volumes:
      #   - name: app-mount
      #     hostPath:
      #       path: /mounted-app-dist
