apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-typescript-debug-example-deployment
spec:
  selector:
    matchLabels:
      app: node-typescript-debug-example
  replicas: 1
  template:
    metadata:
      labels:
        app: node-typescript-debug-example
    spec:
      containers:
        - name: node-typescript-debug-example
          command: ['npm run dev:docker']
          image: node-typescript-debug-example:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app/dist
              name: app-mount
          livenessProbe:
            httpGet:
              path: /
              port: 80
          env:
            - name: NAME
              value: value
      volumes:
        - name: app-mount
          hostPath:
            path: /mounted-app-dist
