version: '3.4'

services:
  node:
    build:
      context: .
      target: debug
      args:
        - NODE_ENV=development         
    command: "npm run nodemon"
    environment:    
      PORT: 5000
    expose:
      - "3000"
      - "9230"
    ports:
      - "5000:5000"
      - "9230:9230"
    volumes:
      - ./dist:/app/dist    