version: '3.4'

services:
  node:
    build:
      context: .
      target: debug
      args:
        - NODE_ENV=development
    command: 'npm run dev:docker'
    environment:
      PORT: 8080
    expose:
      - '8080'
      - '9230'
    ports:
      - '8080:8080'
      - '9230:9230'
    volumes:
      - ./dist:/app/dist
