version: '3.1'

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development         
    command: "npm run nodemon"
    environment:    
      PORT: 3000
    expose:
      - "3000"
      - "9229"
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./dist:/opt/src/app    